import { Lato, Arsenal, Playfair_Display, Cormorant } from "next/font/google";

import "./globals.css";
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});
const lato = Lato({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lato",
  display: "swap",
});
const arsenal = Arsenal({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-arsenal",
  display: "swap",
});

const cormorant = Cormorant({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-cormorant",
});

const getInlineThemeStyle = () => {
  return {
    "--headerColor": "#DF9230" || "",
    "--footerColor": "#CC7506" || "",
    "--contactColor": "#CC7506" || "",
    "--btnHoverColor": "#CC7506" || "",
    "--primaryColor": "#CC7506" || "",
    "--bodyColor": "#CC7506" || "",
  };
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const inlineStyles = getInlineThemeStyle();
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${arsenal.variable}  ${playfair.variable}  ${cormorant.variable}  antialiased`}
        style={inlineStyles}
      >
        {children}
      </body>
    </html>
  );
}
